using System;
using System.Collections.Generic;

namespace Estimate.BusinessEntities
{
    public class CodeLookupCallScriptresponse
    {
        public string Language  { get; set; }
        public string PageTitle  { get; set; }
        public string Intro1  { get; set; }
        public string Intro2  { get; set; }
        public string Intro3  { get; set; }
        public string Intro4  { get; set; }
        public string Intro5  { get; set; }
        public string Intro6  { get; set; }
        public string QMedicareID  { get; set; }
        public string QState  { get; set; }
        public string QEnrollmentYear  { get; set; }
        public string ScriptEnrollBenefits  { get; set; }
        public string QEnrollBenefits  { get; set; }
        public string ScriptElectionPeriod  { get; set; }
        public string QElectionPeriod  { get; set; }
        public string ScriptSEP  { get; set; }
        public string QSEP  { get; set; }
        public string QMemberInfo  { get; set; }
        public string QDOB  { get; set; }
        public string QGender  { get; set; }
        public string QPhone  { get; set; }
        public string QCellPhone  { get; set; }
        public string QAltPhone  { get; set; }
        public string QMAddress  { get; set; }
        public string QEContact  { get; set; }
        public string QEmail  { get; set; }
        public string QPartAandB  { get; set; }
        public string ScriptPremiums  { get; set; }
        public string QPremiumPayment  { get; set; }
        public string ScriptPremiumHelp  { get; set; }
        public string QOtherCoverage  { get; set; }
        public string QLongTermCare  { get; set; }
        public string QMaterialFormat  { get; set; }
        public string QNotMember  { get; set; }
        public string ScriptAuthorized  { get; set; }
        public string QHowYouGotInfo  { get; set; }
        public string OptSpanish  { get; set; }
        public string OptLargePrint  { get; set; }
        public string OptEndingAtt  { get; set; }
        public string ScriptAttestation  { get; set; }
        public string OptYes  { get; set; }
        public string OptNo  { get; set; }
        public string btnSearch  { get; set; }
        public string btnSubmit  { get; set; }
        public string btnClose  { get; set; }
        public string btnCancel  { get; set; }
        public string LabelPrefix  { get; set; }
        public string LabelFirstName  { get; set; }
        public string LabelMI  { get; set; }
        public string LabelLastName  { get; set; }
        public string LabelPermAddress1  { get; set; }
        public string LabelMAddress1  { get; set; }
        public string LabelAddress2  { get; set; }
        public string LabelCity  { get; set; }
        public string LabelState  { get; set; }
        public string LabelZip  { get; set; }
        public string LabelName  { get; set; }
        public string LabelPhone  { get; set; }
        public string LabelRelation  { get; set; }
        public string LabelPartA  { get; set; }
        public string LabelPartB  { get; set; }
        public string LabelCovName  { get; set; }
        public string LabelCovID  { get; set; }
        public string LabelCovGroup  { get; set; }
        public string LabelInstitution  { get; set; }
        public string popMemberFnd  { get; set; }
        public string popSEPNone  { get; set; }
        public string popSSADeduct  { get; set; }
        public string popAttestation1  { get; set; }
        public string popAttestation2  { get; set; }
        public string popAttestation3  { get; set; }
        public string popAttestation4  { get; set; }
        public string popAttestation5  { get; set; }
        public string popAttestation6  { get; set; }
        public string popAttestation7  { get; set; }
        public string popAttestation8  { get; set; }
        public string popAttestation9  { get; set; }
        public string popAttestation10  { get; set; }
        public string popAttestation11  { get; set; }
        public string popAttestation12  { get; set; }
        public string popAttestation14  { get; set; }
        public string popConfirmation  { get; set; }
        public string popCallerObjects  { get; set; }
        public string WantToEnrollYes  { get; set; }
        public string WantToEnrollNo  { get; set; }
        public string popVerifyName  { get; set; }
        public string QPermanentAddress  { get; set; }
        public string popBankAccount  { get; set; }
        public string popCreditCard  { get; set; }
        public string popAttestation9b  { get; set; }
        public string BankAccountDesc  { get; set; }
        public string LabelBAName  { get; set; }
        public string LabelBARouting  { get; set; }
        public string LabelBAAccount  { get; set; }
        public string CreditCardDesc  { get; set; }
        public string LabelCCType  { get; set; }
        public string LabelCCName  { get; set; }
        public string LabelCCAccount  { get; set; }
        public string LabelCCExp  { get; set; }
        public string popUSPSInvalid  { get; set; }
        public string popUSPSUpdate  { get; set; }
        public string popStateValidate  { get; set; }
        public string popStateValidateAlert  { get; set; }
        public string IEPMessage  { get; set; }
        public string AlternateMessage  { get; set; }
        public string popSEPNoneNotAEP  { get; set; }
        public string popMedicareIdAlert  { get; set; }
    }
}
